repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        # Enable verbose output for the 'mypy' hook.
        verbose: true
        # Ignore the exit code of mypy to pass the commit, but still show the output
        entry: bash -c 'mypy "$@" || true' --
  
  - repo: https://github.com/0xsirsaif/pre-commit-taskid
    rev: 0.1.2
    hooks:
      - id: taskid-prepender
        stages: [prepare-commit-msg]